//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotNet.Utils.EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class MENUS
    {
        public decimal ID { get; set; }
        public Nullable<decimal> FATHERID { get; set; }
        public string NAME { get; set; }
        public Nullable<decimal> ISSHOW { get; set; }
        public string URL { get; set; }
        public Nullable<decimal> ORDERS { get; set; }
        public string ICON { get; set; }
        public string SELECTED { get; set; }
    }
}
